# Development environment settings
app:
  version: "1.0.0"
  timezone: "Asia/Ho_Chi_Minh"
  debug: true
  log_level: "debug"

formats:
  date: "%B %d, %Y"

pagination:
  per_page: 10

size_avater: 50
default_size_avater: 80
